/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  getting_started: [
    "getting-started/introduction",
    "getting-started/faq",
    "getting-started/defi-glossary",
    "getting-started/yfi-and-ytokens",
    {
      type: 'category',
      label: 'How to guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started/how-to-guides',
        } 
      ] 
    },
  ],
  partnership: [
    "partnership/introduction"
  ],
  developers: [
    "developers/introduction",
      {
      type: 'category',
      label: 'Smart Contracts',
        items: [
          {
            type: 'autogenerated',
            dirName: 'developers/contracts', // Generate sidebar slice from docs/guides
          } 
        ] 
    },
  ]

};
