export const v3VaultFactoryBlueprintABI = [
  {
    name: 'NewVault',
    inputs: [
      { name: 'vault_address', type: 'address', indexed: true },
      { name: 'asset', type: 'address', indexed: true },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UpdateProtocolFeeBps',
    inputs: [
      { name: 'old_fee_bps', type: 'uint16', indexed: false },
      { name: 'new_fee_bps', type: 'uint16', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UpdateProtocolFeeRecipient',
    inputs: [
      { name: 'old_fee_recipient', type: 'address', indexed: true },
      { name: 'new_fee_recipient', type: 'address', indexed: true },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'UpdateCustomProtocolFee',
    inputs: [
      { name: 'vault', type: 'address', indexed: true },
      { name: 'new_custom_protocol_fee', type: 'uint16', indexed: false },
    ],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'RemovedCustomProtocolFee',
    inputs: [{ name: 'vault', type: 'address', indexed: true }],
    anonymous: false,
    type: 'event',
  },
  { name: 'FactoryShutdown', inputs: [], anonymous: false, type: 'event' },
  {
    name: 'UpdateGovernance',
    inputs: [{ name: 'governance', type: 'address', indexed: true }],
    anonymous: false,
    type: 'event',
  },
  {
    name: 'NewPendingGovernance',
    inputs: [{ name: 'pending_governance', type: 'address', indexed: true }],
    anonymous: false,
    type: 'event',
  },
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'vault_blueprint', type: 'address' },
      { name: 'governance', type: 'address' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'deploy_new_vault',
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'role_manager', type: 'address' },
      { name: 'profit_max_unlock_time', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'vault_blueprint',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'apiVersion',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'protocol_fee_config',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'fee_bps', type: 'uint16' },
          { name: 'fee_recipient', type: 'address' },
        ],
      },
    ],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'set_protocol_fee_bps',
    inputs: [{ name: 'new_protocol_fee_bps', type: 'uint16' }],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'set_protocol_fee_recipient',
    inputs: [{ name: 'new_protocol_fee_recipient', type: 'address' }],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'set_custom_protocol_fee_bps',
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'new_custom_protocol_fee', type: 'uint16' },
    ],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'remove_custom_protocol_fee',
    inputs: [{ name: 'vault', type: 'address' }],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'shutdown_factory',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'set_governance',
    inputs: [{ name: 'new_governance', type: 'address' }],
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    name: 'accept_governance',
    inputs: [],
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'shutdown',
    inputs: [],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'governance',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'pending_governance',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'name',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'default_protocol_fee_config',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'fee_bps', type: 'uint16' },
          { name: 'fee_recipient', type: 'address' },
        ],
      },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'custom_protocol_fee',
    inputs: [{ name: 'arg0', type: 'address' }],
    outputs: [{ name: '', type: 'uint16' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    name: 'use_custom_protocol_fee',
    inputs: [{ name: 'arg0', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
] as const
