module.exports = {
  mySidebar: [
    'faq',
    'links',
    {
      type: 'category',
      label: 'Risks',
      items: [{ type: 'autogenerated', dirName: 'risks' }],
    },
    {
      type: 'category',
      label: 'R & D',
      items: [{ type: 'autogenerated', dirName: 'r-and-d' }],
    },
    'ygift',
    {
      type: 'link',
      href: 'https://github.com/yearn/yearn-pm/tree/master/financials/reports',
      label: 'Financials',
    },
    'defi-glossary',
  ],
}
