 module.exports = {
    mySidebar: [
      'introduction',
      'integration_guide',
      'submit_pr',
      {
          type: 'category',
          label: 'Partners',
          items: [{ type: 'autogenerated', dirName: 'collaborations' }]
      }
    ],
  };
  