export default {
  mySidebar: [
    'index',
    'multisig',
    {
      type: 'category',
      label: 'Risks',
      items: [{ type: 'autogenerated', dirName: 'risks' }],
    },
    'testing',
    'EMERGENCY',
  ],
}
