export default {
  deprecated: [
    {
      type: 'category',
      label: 'Deprecated Projects',
      link: {
        type: 'generated-index',
        title: 'Deprecated Projects',
        slug: '/deprecated',
      },
      items: [{ type: 'autogenerated', dirName: 'deprecated' }],
    },
  ],
}
