module.exports = {
  mySidebar: [
    'faq',
    'links',
    {
      type: 'category',
      label: 'Deprecated Projects',
      items: [{ type: 'autogenerated', dirName: 'deprecated' }],
    },
    {
      type: 'link',
      href: 'https://github.com/yearn/yearn-pm/tree/master/financials/reports',
      label: 'Financials',
    },
    'defi-glossary',
  ],
}
