module.exports = {
    mySidebar: [
        'faq',
        'links',
        {
            type: 'link',
            href: 'https://github.com/yearn/yearn-pm/tree/master/financials/reports',
            label: 'Financials'
        },
        'defi-glossary',
        {
            type: 'category',
            label: 'Risks',
            items: [{ type: 'autogenerated', dirName: 'risks' }]
        }
    ],
};
