export default {
  mySidebar: [
    'building-on-yearn',
    {
      type: 'category',
      label: 'yVaults Version 3',
      link: {
        type: 'doc',
        id: 'v3/overview',
      },
      items: [
        'v3/Integrating_v3',
        'v3/strategy_writing_guide',
        'v3/vault_management',
        'v3/periphery',
        'v3/protocol_fees',
        {
          type: 'category',
          label: '📄 Smart Contracts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v3/smart-contracts',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'yVaults Version 2',
      items: [
        'v2/getting-started',
        'v2/DEPLOYMENT',
        'v2/SPECIFICATION',
        'v2/OPERATIONS',
        'v2/additional-resources',

        {
          type: 'link',
          label: 'Smart Contracts',
          href: '/smart-contracts/V2/BaseStrategy',
        },
      ],
    },
    {
      type: 'category',
      label: 'Yearn Data Services',
      items: [
        'data-services/yearn-data',
        {
          type: 'category',
          label: 'Subgraph',
          items: [
            'data-services/subgraph-info',
            'data-services/entities',
            'data-services/queries',
          ],
        },
        'data-services/yearn-lens',
        'data-services/yearn-api',
      ],
    },
    'front-end-development',
    'v2/naming-convention',
    'v2/EMERGENCY',
    'v2/fork-yearn-ui',
    'v2/ledger-plugin',
    'v2/yswaps',
  ],
}
