module.exports = {
  mySidebar: [
    {
      type: 'category',
      label: 'yVaults Version 3',
      items: [
        'v3/overview',
        'v3/Integrating_v3',
        'v3/strategy_writing_guide',
        'v3/vault_management',
        'v3/periphery',
        'v3/protocol_fees',
        {
          type: 'category',
          label: 'Smart Contracts',
          items: [
            {
              type: 'autogenerated',
              dirName: 'v3/smart-contracts',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'yVaults Version 2',
      items: [
        'v2/getting-started',
        'v2/additional-resources',
        {
          type: 'category',
          label: 'Procedures',
          items: [
            'v2/SPECIFICATION',
            'v2/DEPLOYMENT',
            'v2/OPERATIONS',
            'v2/EMERGENCY',
            'v2/naming-convention',
            'v2/ledger-plugin',
          ],
        },
        {
          type: 'link',
          label: 'Smart Contracts',
          href: '/vaults/smart-contracts/BaseStrategy',
        },
        {
          type: 'category',
          label: 'Yearn Data Services',
          link: {
            type: 'doc',
            id: 'v2/yearn-data',
          },
          items: [
            {
              type: 'link',
              label: 'yDaemon',
              href: 'https://ydaemon.yearn.farm/docs/intro',
            },
            {
              type: 'category',
              label: 'Subgraphs',
              link: {
                type: 'doc',
                id: 'v2/subgraph-info',
              },
              items: ['v2/entities', 'v2/queries'],
            },
            'v2/yearn-lens',
          ],
        },
        'v2/hacking-with-yearn',
        'v2/fork-yearn-ui',
        'v2/yswaps',
      ],
    },
  ],
}
